# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
random = np.empty((3,3,3))
random

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [7.56602523e-307, 4.45060183e-308, 1.29061821e-306],
        [9.34608432e-307, 7.56599807e-307, 8.90104239e-307]],

       [[1.24610383e-306, 1.69118108e-306, 8.06632139e-308],
        [1.20160711e-306, 1.69119330e-306, 8.90098127e-307],
        [1.95820216e-306, 7.56604561e-307, 8.45590539e-307]],

       [[1.11261298e-306, 6.23054633e-307, 1.42418036e-306],
        [9.34598247e-307, 9.79094970e-307, 1.78019354e-306],
        [1.69120552e-306, 2.56765117e-312, 2.25179982e+015]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
diagonal = np.diag(1+np.arange(4), k = -1)
diagonal

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
checkerboard = np.ones((3,3))
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [6]:
a= np.random.random((5,5))
print("Before normalization:")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

Before normalization:
[[0.13661851 0.30302476 0.67338407 0.16506119 0.88480206]
 [0.52766898 0.94303579 0.85340628 0.66037416 0.49089887]
 [0.70896549 0.29059202 0.70674235 0.73793424 0.13382216]
 [0.85990855 0.41130809 0.71558658 0.09041895 0.51363893]
 [0.15999134 0.95425936 0.19400124 0.51205752 0.37898112]]
After normalization:
[[0.05348159 0.246117   0.6748528  0.08640745 0.91959476]
 [0.50616992 0.98700736 0.88325033 0.65979225 0.46360406]
 [0.71604261 0.2317246  0.71346905 0.74957745 0.05024447]
 [0.8907775  0.37146808 0.72370732 0.         0.48992844]
 [0.08053848 1.         0.11990906 0.48809777 0.3340457 ]]


# 5.  How to find common values between two arrays?

In [7]:
array1 = np.array([2,4,6,8,10])
print("Array1: ",array1)

array2 = [6,8,12]
print("Array2: ",array2)

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 2  4  6  8 10]
Array2:  [6, 8, 12]
Common values between two arrays:
[6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)

today     = np.datetime64('today', 'D')
print("Today: ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [12]:
array1 = np.random.random((3,3))
print("First array:")
print(array1)

array2 = np.random.random((3,3))
print("Second array:")
print(array2)

print("Check if they are equal?")
equal = np.allclose(array1, array2)
print(equal)

First array:
[[0.95893117 0.90581182 0.84439266]
 [0.33499823 0.15246223 0.07407932]
 [0.31486624 0.36467262 0.25892723]]
Second array:
[[0.84364831 0.37981678 0.55245064]
 [0.16669008 0.66994584 0.73564266]
 [0.27562436 0.94452647 0.50993025]]
Check if they are equal?
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [13]:
vector = np.random.random(10)
print("Array: ")
print(vector)

vector[vector.argmax()] = 0
print("Maximum value replaced by 0:")
print(vector)

Array: 
[0.29894214 0.00863961 0.75630954 0.96626873 0.46664897 0.34424722
 0.28666468 0.35440298 0.47343093 0.0071753 ]
Maximum value replaced by 0:
[0.29894214 0.00863961 0.75630954 0.         0.46664897 0.34424722
 0.28666468 0.35440298 0.47343093 0.0071753 ]


# 9. How to print all the values of an array?

In [16]:
import sys
a = np.ones((6,6))
np.set_printoptions(threshold=sys.maxsize)
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [17]:
matrix = np.random.rand(4,4)
print(matrix)
print("\nSubtract the mean of each row of the said matrix:\n")
mean = matrix - matrix.mean(axis=1, keepdims=True)
print(mean)


[[0.43843885 0.94547758 0.81071598 0.92390736]
 [0.26253192 0.84543532 0.96949663 0.56937148]
 [0.85421948 0.6002792  0.3584616  0.05412524]
 [0.73455829 0.88788505 0.03277996 0.3284801 ]]

Subtract the mean of each row of the said matrix:

[[-0.34119609  0.16584264  0.03108104  0.14427242]
 [-0.39917692  0.18372648  0.3077878  -0.09233736]
 [ 0.3874481   0.13350783 -0.10830978 -0.41264614]
 [ 0.23863244  0.3919592  -0.46314589 -0.16744575]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
a = np.ones(5)
print(a)

b = np.random.randint(0,len(a),10)
print(b)

a += np.bincount(b, minlength=len(a))
print(a)


[1. 1. 1. 1. 1.]
[0 3 4 3 3 0 1 1 0 2]
[4. 3. 2. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [19]:
a = np.arange(9).reshape(3, 3)
print(a,"\n")

b = np.arange(9).reshape(3, 3)
print(b,"\n")

c = np.diag(a.dot(b))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[ 15  54 111]


# 13.How to find the most frequent value in an array?

In [21]:
array = np.random.randint(0,10,50)
print(array)

print("Most frequent value in the above array:")
print(np.bincount(array).argmax())

[9 1 1 8 3 2 4 9 0 0 6 1 7 7 6 4 0 8 7 3 1 9 4 2 4 6 5 2 4 4 6 9 8 9 5 0 5
 1 3 6 9 3 1 1 9 3 9 3 3 6]
Most frequent value in the above array:
9


# 14.How to get the n largest values of an array

In [23]:
a = np.array([10,5,6,12,54,23,87,101,567,234])
print(a)
n = 3
print("Maximum value is:")
print (a[np.argsort(a)[-n:]])


[ 10   5   6  12  54  23  87 101 567 234]
Maximum value is:
[101 234 567]


# 15.How to create a record array from a regular array?

In [25]:
a = np.array(['Jesse','Gustavo','Heisenberg'])
b = np.array([96.2,1213,55])
c = np.array(['pinkman','fring','White'])
result= np.core.records.fromarrays([a, b, c])
print(result[0])
print(result[1])
print(result[2])

('Jesse', 96.2, 'pinkman')
('Gustavo', 1213., 'fring')
('Heisenberg', 55., 'White')
